### ISSUE TITLE
현재 오류 about (this)

### ISSUE THREAD

**Issue by yu01203** [kmdiabolos/MiniChatAPP#1]
클라이언트에서 클라이언트 리시버로 this 값을 넘겨야 하는데 this 값을 정확히 몰라서 어떤 것을 넘겨야 할지 정해주지 못하고 있다.

**Comment by kmdiabolos** [comment]
disConnect를 implements 하고 disConnect를 선언해주는것으로 해결함.

**Comment by kmdiabolos** [comment]
disConnect를 implements 하고 disConnect를 선언해주는것으로 해결함.
