### ISSUE TITLE
강제종료 (구조적오류)

### ISSUE THREAD

**Issue by yu01203** [kmdiabolos/MiniChatAPP#2]
처음 켜자마자 접속 컴퓨터 ip (차후 서버 ip로 변경) 입력도 안들어가며 구조적 오류로 강제종료됨.

**Comment by yu01203** [comment]
+ 계속 하다보니 소켓 연결이 제대로 안되는 것 같은데 아직도 해결이 안됨.

**Comment by kmdiabolos** [comment]
onCreate밖의 함수에서 호출하여 종료가되는거 같음

**Comment by kmdiabolos** [comment]
기존의 함수들을 onCreate안에 집어넣어 해결하였음.
